/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Challenge, VibeType } from './types';

// Squad Mode 
export const SQUAD_CARDS: Record<VibeType, Partial<Challenge>[]> = {
  Icebreaker: [
    { text: "{player} has to speak in an accent for the next 3 turns. Everyone votes on which accent.", punishment: 2 },
    { text: "Everyone who has ever lied to get out of plans drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must text the last person they spoke to 'I have a confession' and show the reply.", punishment: 2 },
    { text: "The tallest person in the room drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must do their best celebrity impression. Group votes — bad performance means {sips} sips.", punishment: 2 },
    { text: "Everyone who has stalked an ex on social media drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must say something nice about every person in the room or drink {sips} sips.", punishment: 2 },
    { text: "The person who woke up latest today drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must name 5 countries in 10 seconds or drink {sips} sips.", punishment: 3 },
    { text: "Everyone who has pretended to be busy to avoid someone drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must do 10 jumping jacks or drink {sips} sips.", punishment: 2 },
    { text: "The person with the most unread messages drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must speak only in questions for the next 2 turns or drink {sips} sips per mistake.", punishment: 1 },
    { text: "Everyone who has laughed at the wrong moment drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let someone else post anything on their story or drink {sips} sips.", punishment: 3 },
    { text: "The person who last cried at a movie drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must list 5 things they like about themselves in 15 seconds or drink {sips} sips.", punishment: 2 },
    { text: "Everyone who has forgotten someone's name mid-conversation drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must call someone random from their contacts and say 'I miss you' or drink {sips} sips.", punishment: 4 },
    { text: "The youngest person drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must show their most embarrassing photo or drink {sips} sips.", punishment: 3 },
    { text: "Everyone who has ghosted someone drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let the group send one text from their phone or drink {sips} sips.", punishment: 3 },
    { text: "The person who last Googled something embarrassing drinks {sips} sips — show it or drink 3.", punishment: 2, type: 'GROUP' },
    { text: "{player} must do a 30 second stand-up comedy set about themselves.", punishment: 2 },
    { text: "Everyone who has eaten food that fell on the floor drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must swap seats with someone for the next 3 turns.", punishment: 2 },
    { text: "The person who takes the longest to get ready drinks {sips} sips — group decides.", punishment: 2, type: 'GROUP' },
    { text: "{player} must compliment every person in the room with a different compliment.", punishment: 2 },
    { text: "Everyone who has replied 'on my way' while still at home drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must do their best dance move for 15 seconds.", punishment: 2 },
    { text: "The person with the most apps on their phone drinks {sips} sips — show the screen.", punishment: 2, type: 'GROUP' },
    { text: "{player} must talk in slow motion for the next 2 turns or drink {sips} sips per mistake.", punishment: 1 },
    { text: "Everyone who has pretended to laugh at a joke they didn't get drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let someone read their last 5 voice notes or drink {sips} sips.", punishment: 3 },
    { text: "The person who last cancelled plans drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must do an impression of the person to their left.", punishment: 2 },
    { text: "Everyone who has accidentally liked an old post while stalking someone drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal the last thing they searched on YouTube.", punishment: 2 },
    { text: "The person who talks the most drinks {sips} sips — group vote.", punishment: 2, type: 'GROUP' },
    { text: "{player} must answer the next question from another player honestly or drink {sips} sips.", punishment: 3 },
    { text: "Everyone who has fallen asleep during a movie they suggested drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let someone scroll through their camera roll for 15 seconds.", punishment: 2 },
    { text: "The person who arrives latest to things drinks {sips} sips — group vote.", punishment: 2, type: 'GROUP' },
    { text: "{player} must do a dramatic reading of their most recent sent text.", punishment: 2 },
    { text: "Everyone who has run a red light drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must reveal their most used emoji and explain why.", punishment: 2 },
    { text: "The shortest person drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must name every person in the room and say one word that describes them.", punishment: 2 },
    { text: "Everyone who has sung loudly alone in the car drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must reveal the last person they searched on Instagram.", punishment: 2 },
    { text: "The oldest person drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must close their eyes and point to someone — that person asks them any question.", punishment: 2 },
    { text: "Everyone who has pretended not to see someone in public drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must speak in third person for the next 3 turns or drink {sips} sips per mistake.", punishment: 1 },
    { text: "The person who last told a white lie drinks {sips} sips — honour system.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal their most embarrassing autocorrect fail.", punishment: 2 },
    { text: "Everyone who has drunk juice straight from the carton drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let someone change their profile picture for the rest of the game.", punishment: 2 },
    { text: "The person with the most social media followers drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must say a tongue twister 3 times fast or drink {sips} sips.", punishment: 2 },
    { text: "Everyone who has snooped through someone else's phone drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must reveal the last thing they deleted from their phone.", punishment: 2 },
    { text: "The person who sleeps the most drinks {sips} sips — group vote.", punishment: 2, type: 'GROUP' },
    { text: "{player} must do an impression of their own parents.", punishment: 2 },
    { text: "Everyone who has faked being sick to skip something drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let the group pick a song and they must lip sync it.", punishment: 2 },
    { text: "The person who swears the most drinks {sips} sips — group vote.", punishment: 2, type: 'GROUP' },
    { text: "{player} must read the last paragraph of the last article they read online.", punishment: 2 },
    { text: "Everyone who has told a secret they were supposed to keep drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must give a dramatic weather forecast for the rest of the evening.", punishment: 2 },
    { text: "The person who eats the most drinks {sips} sips — group vote.", punishment: 2, type: 'GROUP' },
    { text: "{player} must whisper everything they say for the next 2 turns.", punishment: 2 },
    { text: "Everyone who has returned something after using it drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let someone style their hair however they want.", punishment: 2 },
    { text: "The person who laughs the most drinks {sips} sips — group vote.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal the most expensive thing they have ever bought for themselves.", punishment: 2 },
    { text: "Everyone who has eaten in bed drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must speak only using song lyrics for the next 2 turns or drink {sips} sips per mistake.", punishment: 1 },
    { text: "The person who texts the fastest drinks {sips} sips — group vote.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal what they were doing at midnight last night.", punishment: 2 },
    { text: "Everyone who has double texted someone drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must do 20 seconds of continuous beatboxing.", punishment: 2 },
    { text: "The person who went to bed latest last night drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must let someone else order their next drink or snack.", punishment: 2 },
    { text: "Everyone who has downloaded then immediately deleted a dating app drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must tell the group about the most awkward date they have ever been on.", punishment: 2 },
    { text: "The person who has the most photos on their phone drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must do 5 push-ups right now or drink {sips} sips.", punishment: 3 },
    { text: "Everyone who has talked to themselves out loud when alone drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must let the group go through their Spotify or Apple Music history.", punishment: 2 },
    { text: "The person who has the most contacts in their phone drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reenact their morning routine in 30 seconds.", punishment: 2 },
    { text: "Everyone who has binge watched an entire series in one day drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must reveal the last compliment they gave someone and who it was.", punishment: 2 },
    { text: "The person who has worked the longest without a break drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must let someone read the last voice message they received out loud.", punishment: 2 },
    { text: "Everyone who has judged someone based on their playlist drinks {sips} sips.", punishment: 1, type: 'GROUP' },
    { text: "{player} must do a dramatic monologue about their week.", punishment: 2 },
    { text: "Last card — everyone drinks {sips} sips together to close the round. Cheers!", punishment: 2, type: 'GROUP' },
  ],
  Arena: [
    { text: "{player} must down their entire drink or do 15 push-ups right now.", punishment: 4 },
    { text: "The two people who have been friends the longest must reveal one secret about each other.", punishment: 3, type: 'GROUP' },
    { text: "{player} is on a rule — every time they use someone's name they drink {sips} sips.", punishment: 1 },
    { text: "Everyone must rank the other players by attractiveness out loud or drink {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let the group choose one embarrassing thing they must post on their story.", punishment: 4 },
    { text: "The person who has had the most relationships drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — arm wrestle. Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "Everyone must confess the most recent lie they told or drink {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must do 20 squats right now or drink {sips} sips.", punishment: 4 },
    { text: "The person who the group thinks is the biggest flirt drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let someone go through their DMs for 30 seconds or drink {sips} sips.", punishment: 4 },
    { text: "Everyone who has cheated at a board game drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal the most embarrassing thing they have done to impress someone.", punishment: 3 },
    { text: "The person who the group thinks is the worst driver drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — staring contest. First to blink drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "Everyone must reveal their most toxic trait or drink {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must call someone they haven't spoken to in over a year or drink {sips} sips.", punishment: 5 },
    { text: "The person who has blocked the most people drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the pettiest thing they have ever done to an ex.", punishment: 3 },
    { text: "Everyone must vote — who in the room would survive a zombie apocalypse last? That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let someone send a message to anyone in their contacts or drink {sips} sips.", punishment: 5 },
    { text: "The person who the group thinks spends the most money drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — thumb war. Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "Everyone must reveal the most desperate thing they have done for attention or drink {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must do a plank for 45 seconds or drink {sips} sips.", punishment: 4 },
    { text: "The person who has been rejected the most drinks {sips} sips — honour system.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the most scandalous rumour they have ever spread.", punishment: 3 },
    { text: "Everyone votes — who in the room is most likely to get arrested? That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let the group read their last 10 texts or drink {sips} sips.", punishment: 5 },
    { text: "The person who the group thinks is the most stubborn drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must do 30 seconds of continuous exercise chosen by the group or drink {sips} sips.", punishment: 4 },
    { text: "Everyone must reveal the most embarrassing thing that has happened to them in public.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — who can hold their breath longest. Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "The person with the most exes drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the most expensive mistake they have ever made.", punishment: 3 },
    { text: "Everyone votes — who in the room would be the worst partner? That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let the group pick a stranger's profile online and roast them together.", punishment: 3 },
    { text: "The person who has kissed the most people in this room drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must confess the biggest secret they have kept from their best friend.", punishment: 4 },
    { text: "Everyone must rank themselves in terms of intelligence out loud or drink {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — whoever laughs first drinks {sips} sips. Start telling each other jokes.", punishment: 5, type: 'GROUP' },
    { text: "The person who has cried the most this year drinks {sips} sips — honour system.", punishment: 3, type: 'GROUP' },
    { text: "{player} must do 15 burpees or drink {sips} sips.", punishment: 5 },
    { text: "Everyone must reveal the worst thing they have ever done to a friend or drink {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} must let the group change their WhatsApp status for the rest of the game.", punishment: 4 },
    { text: "The person who talks about themselves the most drinks {sips} sips — group vote.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — who can do the most sit-ups in 30 seconds. Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "Everyone must confess who in the room they trust the least or drink {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} must show the most cringe thing saved on their phone or drink {sips} sips.", punishment: 4 },
    { text: "The person who the group thinks is the most dramatic drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the biggest fight they have ever been in and what it was about.", punishment: 3 },
    { text: "Everyone votes — who in the room is most likely to be famous one day? Runner up drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must do 20 push-ups or drink {sips} sips.", punishment: 5 },
    { text: "The person who has spent the most money on someone who didn't deserve it drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let someone post a tweet or status from their account or drink {sips} sips.", punishment: 5 },
    { text: "Everyone must reveal who their least favourite person in the room is right now or drink {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} vs {player} — who can keep a straight face longest while the group tries to make them laugh. Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "The person who has the messiest room drinks {sips} sips — group vote.", punishment: 3, type: 'GROUP' },
    { text: "{player} must confess the most selfish thing they have ever done.", punishment: 3 },
    { text: "Everyone votes — who in the room has changed the most in the last year? That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal what they actually think of everyone's relationship choices in the room.", punishment: 3 },
    { text: "The person who has cancelled plans the most this month drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — dance battle. Group votes on winner. Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "Everyone must confess the most manipulative thing they have ever done or drink {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} must let the group pick someone for them to compliment via text right now.", punishment: 3 },
    { text: "The person who the group thinks is the most two-faced drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the most embarrassing thing they have ever sent to the wrong person.", punishment: 3 },
    { text: "Everyone votes — who in the room is most likely to get married next? That person assigns {sips} sips to anyone.", punishment: 3, type: 'GROUP' },
    { text: "{player} must do a 60 second workout of the group's choosing or drink {sips} sips.", punishment: 5 },
    { text: "The person who gossips the most drinks {sips} sips — group vote.", punishment: 3, type: 'GROUP' },
    { text: "{player} must confess the biggest lie they have ever told in this friend group.", punishment: 4 },
    { text: "Everyone must reveal their most controversial opinion or drink {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — who can do more push-ups in 30 seconds. Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "The person who has stood someone up before drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let someone reply to their last Instagram comment or drink {sips} sips.", punishment: 4 },
    { text: "Everyone votes — who in the room would be the worst roommate? That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the most embarrassing thing they have googled in the last week.", punishment: 3 },
    { text: "The person who has been blocked by the most people drinks {sips} sips — honour system.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — who knows the other better. Ask 3 questions each. Most wrong answers drinks {sips} sips.", punishment: 5, type: 'GROUP' },
    { text: "Everyone must reveal what they actually think about someone's life choices in the room or drink {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} must confess the worst date they have ever been on in full detail.", punishment: 3 },
    { text: "The person who has the most situationships drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let the group go through their saved posts on Instagram or drink {sips} sips.", punishment: 4 },
    { text: "Everyone votes — who in the room is the biggest overthinker? That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the most embarrassing voicemail they have ever left someone.", punishment: 3 },
    { text: "The person who the group thinks has the worst taste in partners drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} vs {player} — who can stay silent the longest. First to speak drinks {sips} sips.", punishment: 5, type: 'GROUP' },
    { text: "Everyone must confess the most childish thing they still do as an adult or drink {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the thing they are most insecure about or drink {sips} sips.", punishment: 4 },
    { text: "The person who has spent the most money on a night out drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let someone read their most recent DM conversation out loud or drink {sips} sips.", punishment: 5 },
    { text: "Everyone votes — who in the room is most likely to ghost someone this year? That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must do 25 jumping jacks right now or drink {sips} sips.", punishment: 4 },
    { text: "The person who cares the most about what others think drinks {sips} sips — group vote.", punishment: 3, type: 'GROUP' },
    { text: "{player} must confess the most embarrassing thing they have ever done while drunk.", punishment: 4 },
    { text: "Everyone must reveal the most recent thing they lied about or drink {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} vs {player} — rap battle. 30 seconds each. Group votes. Loser drinks {sips} sips.", punishment: 5, type: 'GROUP' },
    { text: "The person who has the most unresolved beef with someone drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal one thing about themselves that would shock everyone in the room.", punishment: 4 },
    { text: "Final card — the person with the most sips must finish their drink. Everyone else drinks {sips} sips.", punishment: 3, type: 'GROUP' },
  ],
  AfterDark: [
    { text: "{player} must whisper a graphic fantasy into the ear of the person to their left or drink {sips} sips.", punishment: 4 },
    { text: "{player} and {player} must have a 'slow dance' for 30 seconds with no music or both drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe their favorite sexual position in detail or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let the person to their right trace their lips with a finger or drink {sips} sips.", punishment: 3 },
    { text: "{player} must reveal the most sensitive spot on their body or drink {sips} sips.", punishment: 4 },
    { text: "Everyone must vote on who has the best 'bedroom eyes.' That person drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must sit on the lap of the person they find most attractive for 2 rounds or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the group decide which two players they have to 'Seven Minutes in Heaven' with.", punishment: 0 },
    { text: "{player} must describe the most scandalous thing they’ve done in a car or drink {sips} sips.", punishment: 4 },
    { text: "{player} vs {player} — Twerk-off. The group votes the winner. Loser drinks {sips} sips.", punishment: 5, type: 'GROUP' },
    { text: "{player} must let the person across from them give them a neck hickey or drink {sips} sips.", punishment: 6 },
    { text: "{player} must reveal if they have ever 'faked it' or drink {sips} sips.", punishment: 4 },
    { text: "{player} must remove one item of clothing using only their teeth or drink {sips} sips.", punishment: 5 },
    { text: "{player} must whisper the name of the player they’d most like to see naked to the group or drink {sips} sips.", punishment: 4 },
    { text: "Everyone who is currently wearing 'spicy' underwear drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must give the person to their right a 1-minute sensual massage or drink {sips} sips.", punishment: 4 },
    { text: "{player} must reveal the most public place they’ve ever had sex or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} reach under their shirt for 20 seconds or drink {sips} sips.", punishment: 5 },
    { text: "{player} must demonstrate their 'O-face' to the group or drink {sips} sips.", punishment: 5 },
    { text: "{player} must confess the weirdest thing that turns them on or drink {sips} sips.", punishment: 4 },
    { text: "{player} must lick a path from {player}'s wrist to their elbow or drink {sips} sips.", punishment: 4 },
    { text: "{player} must send a 'Thinking of you' text to their last hookup or drink {sips} sips.", punishment: 6 },
    { text: "{player} and {player} must swap shirts right now or both drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the group choose a player to give them a 'body shot' or drink {sips} sips.", punishment: 6 },
    { text: "Everyone must vote on who is most likely to have a secret OnlyFans. That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must show the group the last 'thirst trap' they took or drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe what {player} smells like in a provocative way or drink {sips} sips.", punishment: 3 },
    { text: "{player} must do 10 'erotic' push-ups over {player} or drink {sips} sips.", punishment: 5 },
    { text: "{player} must reveal their body count or drink {sips} sips.", punishment: 6 },
    { text: "{player} must let the person to their left unbutton two buttons on their shirt or drink {sips} sips.", punishment: 4 },
    { text: "{player} vs {player} — Who can make the most convincing 'moan'? Loser drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} must reveal if they’ve ever had a crush on someone in this room or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the group see their 'hidden' or 'archived' photos for 10 seconds or drink {sips} sips.", punishment: 7 },
    { text: "{player} must describe the best sex they’ve ever had or drink {sips} sips.", punishment: 4 },
    { text: "{player} must kiss the inner thigh of the person to their left or drink {sips} sips.", punishment: 6 },
    { text: "Everyone who has ever had a one-night stand drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal their most embarrassing 'bedroom' fail or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} bite their earlobe for 10 seconds or drink {sips} sips.", punishment: 4 },
    { text: "{player} must sit behind {player} and wrap their arms around them for 3 rounds or drink {sips} sips.", punishment: 5 },
    { text: "{player} must reveal the most people they’ve slept with in one week or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let the group decide which player gets to slap their ass or drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe what they find most attractive about the person to their right or drink {sips} sips.", punishment: 3 },
    { text: "{player} must do a 'lap dance' for 30 seconds for the person of their choice or drink {sips} sips.", punishment: 6 },
    { text: "Everyone who has ever sent a 'nude' drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the last time they watched porn or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} put an ice cube down their shirt or drink {sips} sips.", punishment: 5 },
    { text: "{player} must whisper a 'dirty' secret to {player} or drink {sips} sips.", punishment: 4 },
    { text: "{player} must reveal if they prefer 'rough' or 'gentle' or drink {sips} sips.", punishment: 3 },
    { text: "{player} must let the group pick a player to give them a 'butterfly kiss' on the neck or drink {sips} sips.", punishment: 4 },
    { text: "{player} must take off their socks using only their teeth or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} use their tongue to find a 'sweet spot' on their neck or drink {sips} sips.", punishment: 6 },
    { text: "{player} must reveal the most 'adventurous' place they want to have sex or drink {sips} sips.", punishment: 4 },
    { text: "{player} must crawl across the floor to {player} in a 'sexy' way or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the person across from them feed them a drink like a baby or drink {sips} sips.", punishment: 4 },
    { text: "Everyone must vote on who is the 'freakiest' in the room. That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let {player} 'inspect' their underwear color and announce it or drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe their favorite thing to do in bed or drink {sips} sips.", punishment: 5 },
    { text: "{player} must give {player} a 'wet' kiss on the cheek or drink {sips} sips.", punishment: 4 },
    { text: "{player} must reveal if they have ever been caught 'in the act' or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the person to their right put their hand in their back pocket for 2 rounds or drink {sips} sips.", punishment: 5 },
    { text: "{player} must tell the group which player has the best lips or drink {sips} sips.", punishment: 4 },
    { text: "{player} vs {player} — Staring contest while holding hands. First to break eye contact drinks {sips} sips.", punishment: 4, type: 'GROUP' },
    { text: "{player} must reveal their 'morning after' routine or drink {sips} sips.", punishment: 3 },
    { text: "{player} must let {player} draw a heart on their chest with their tongue or drink {sips} sips.", punishment: 7 },
    { text: "Everyone who has ever had a 'friends with benefits' drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the most 'toxic' sexual thing they enjoy or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the group choose two people to 'spoon' on the floor or they both drink {sips} sips.", punishment: 6 },
    { text: "{player} must describe the most 'unusual' place they’ve been turned on or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} whisper 'filth' in their ear for 10 seconds or drink {sips} sips.", punishment: 5 },
    { text: "{player} must reveal their biggest 'turn-off' in the bedroom or drink {sips} sips.", punishment: 3 },
    { text: "{player} must give a 'bedroom' rating (1-10) for everyone in the room or drink {sips} sips.", punishment: 6 },
    { text: "{player} must let {player} bite their lip or drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe the first time they ever had sex or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the group decide which player they have to French kiss or drink {sips} sips.", punishment: 8 },
    { text: "Everyone must vote on who is most likely to have a 'work spouse.' That person drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal if they’ve ever 'done it' in a group setting or drink {sips} sips.", punishment: 6 },
    { text: "{player} must let {player} use their mouth to move a piece of clothing on them or drink {sips} sips.", punishment: 6 },
    { text: "{player} must show their 'sexy' walk to the group or drink {sips} sips.", punishment: 4 },
    { text: "{player} must reveal the last person they had a sexual dream about or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let {player} sit on their back while they do 5 push-ups or drink {sips} sips.", punishment: 5 },
    { text: "{player} must tell the group their favorite 'pet name' to be called or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let the person to their left give them a 'hickey' on the shoulder or drink {sips} sips.", punishment: 6 },
    { text: "{player} must reveal if they have ever used 'toys' during sex or drink {sips} sips.", punishment: 4 },
    { text: "{player} vs {player} — Who can stay 'serious' while the other tries to seduce them? Loser drinks {sips} sips.", punishment: 5, type: 'GROUP' },
    { text: "{player} must describe what they are wearing underneath their clothes in graphic detail or drink {sips} sips.", punishment: 5 },
    { text: "Everyone who has ever slept with an ex drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must let {player} lick an ice cube off their neck or drink {sips} sips.", punishment: 6 },
    { text: "{player} must reveal the 'wildest' thing on their bucket list or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let the group choose a player to 'grind' on them for 15 seconds or drink {sips} sips.", punishment: 7 },
    { text: "{player} must tell the group which player they’d choose for a 'threesome' or drink {sips} sips.", punishment: 6 },
    { text: "{player} must reveal if they’ve ever walked in on their parents or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} blow hot air on their inner thigh or drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe their 'ideal' partner in bed or drink {sips} sips.", punishment: 3 },
    { text: "{player} must let the person to their right 'mark' them with a pen on a private area or drink {sips} sips.", punishment: 6 },
    { text: "Everyone who has ever had a 'crush' on a teacher drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal the most 'risky' photo they’ve ever received or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let {player} 'choke' them lightly (if consensual) for 5 seconds or drink {sips} sips.", punishment: 6 },
    { text: "{player} must tell the group their favorite 'dirty' word or drink {sips} sips.", punishment: 3 },
    { text: "{player} must let the group decide which two players have to make out or both drink {sips} sips.", punishment: 8 },
    { text: "{player} must remove their shirt for the next 5 rounds or drink {sips} sips.", punishment: 7 },
    { text: "{player} must reveal if they have ever 'hooked up' with a friend's ex or drink {sips} sips.", punishment: 6 },
    { text: "{player} must let {player} massage their inner thighs for 30 seconds or drink {sips} sips.", punishment: 6 },
    { text: "{player} must describe their most 'unforgettable' kiss or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let the person to their left 'blindfold' them and kiss them or drink {sips} sips.", punishment: 6 },
    { text: "Everyone must vote on who has the 'hottest' body in the room. That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal if they’ve ever 'joined the mile high club' or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let {player} use their teeth to remove a piece of clothing or drink {sips} sips.", punishment: 7 },
    { text: "{player} must show their 'stripper name' and 'stripper move' or drink {sips} sips.", punishment: 5 },
    { text: "{player} must reveal the last time they were 'rejected' in the bedroom or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} pour a drink into their mouth while sitting on their lap or drink {sips} sips.", punishment: 6 },
    { text: "{player} must tell the group their favorite 'after-care' activity or drink {sips} sips.", punishment: 3 },
    { text: "{player} must let the group choose a player to 'spank' them or drink {sips} sips.", punishment: 5 },
    { text: "{player} must reveal the most 'shameful' thing they’ve done for sex or drink {sips} sips.", punishment: 6 },
    { text: "{player} must let {player} trace their 'V-line' with a finger or drink {sips} sips.", punishment: 6 },
    { text: "Everyone who has ever been 'friend-zoned' drinks {sips} sips.", punishment: 2, type: 'GROUP' },
    { text: "{player} must reveal if they prefer 'lights on' or 'lights off' or drink {sips} sips.", punishment: 3 },
    { text: "{player} must let {player} lick their earlobe for 10 seconds or drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe their 'dream' threesome including one player from the room or drink {sips} sips.", punishment: 7 },
    { text: "{player} must reveal the most 'awkward' thing that’s happened during sex or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} put their hands down the back of their pants for 1 round or drink {sips} sips.", punishment: 7 },
    { text: "{player} must tell the group which player they think is the most 'submissive' or drink {sips} sips.", punishment: 4 },
    { text: "{player} vs {player} — Who can make the 'sexiest' face? Group votes. Loser drinks {sips} sips.", punishment: 5, type: 'GROUP' },
    { text: "{player} must reveal if they’ve ever used a 'dating app' for a one-night stand or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} give them a 'butterfly kiss' on the stomach or drink {sips} sips.", punishment: 6 },
    { text: "Everyone who has ever had 'shower sex' drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal the most 'daring' text they’ve ever sent or drink {sips} sips.", punishment: 5 },
    { text: "{player} must let the person to their right 'bite' their shoulder or drink {sips} sips.", punishment: 5 },
    { text: "{player} must describe their favorite 'lingerie' or 'underwear' type or drink {sips} sips.", punishment: 3 },
    { text: "{player} must let {player} 'cradle' them like a baby for 1 minute or drink {sips} sips.", punishment: 5 },
    { text: "{player} must reveal if they have ever 'caught feelings' for a hookup or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let the group choose which player they have to 'make out' with for 10 seconds or drink {sips} sips.", punishment: 8 },
    { text: "{player} must tell the group their 'secret' turn-on or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} 'straddle' them for 1 full round or drink {sips} sips.", punishment: 7 },
    { text: "{player} must reveal if they’ve ever 'ghosted' someone after sex or drink {sips} sips.", punishment: 5 },
    { text: "Everyone must vote on who is most likely to be a 'dom.' That person drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal their favorite 'spot' to be touched or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let {player} give them a 'wet' kiss on the neck or drink {sips} sips.", punishment: 6 },
    { text: "{player} must describe their 'wildest' fantasy involving someone in this room or drink {sips} sips.", punishment: 8 },
    { text: "{player} must reveal the 'biggest' lie they’ve told to get someone into bed or drink {sips} sips.", punishment: 6 },
    { text: "{player} must let the person across from them 'check' if they are wearing a bra or underwear or drink {sips} sips.", punishment: 6 },
    { text: "{player} must tell the group who they think is the 'best' at kissing in the room or drink {sips} sips.", punishment: 5 },
    { text: "{player} vs {player} — 'Sexy' thumb war. Winner gets to give the loser a hickey or loser drinks {sips} sips.", punishment: 7, type: 'GROUP' },
    { text: "{player} must reveal if they have ever had a 'threesome' or drink {sips} sips.", punishment: 6 },
    { text: "{player} must let {player} 'nibble' on their neck for 15 seconds or drink {sips} sips.", punishment: 6 },
    { text: "Everyone who has ever 'cried' after sex drinks {sips} sips.", punishment: 3, type: 'GROUP' },
    { text: "{player} must reveal their favorite 'position' for a quickie or drink {sips} sips.", punishment: 4 },
    { text: "{player} must let the person to their left 'unzip' or 'unbutton' one item of clothing or drink {sips} sips.", punishment: 7 },
    { text: "{player} must tell the group their 'number' or drink 10 sips.", punishment: 10 },
    { text: "{player} must let {player} 'grind' against them while they both drink or drink {sips} sips.", punishment: 8 },
    { text: "Everyone must take a 'group shot' and reveal one 'dirty' secret together.", punishment: 0, type: 'GROUP' },
  ]
};

// Couples Mode (Wheel Style)
export const COUPLES_TRUTHS: string[] = [
  "What is the one thing about me that you find irresistible?",
  "Have you ever fantasised about someone else while with me?",
  "What is the boldest move you have ever made to get someone's attention?",
  "What is something physical about me that you love but have never told me?",
  "Have you ever read my messages without me knowing?",
  "What is the one place you have always wanted to be intimate with me?",
  "Have you ever lied to me about where you were?",
  "What is your favourite memory of us being physical together?",
  "What is something you wish I would do more of in our relationship?",
  "Have you ever been attracted to one of my friends?",
  "What is the most daring thing you have ever done in a relationship?",
  "What is something I do that drives you absolutely wild?",
  "Have you ever kept a secret from me that you still haven't told me?",
  "What is a fantasy you have that you have been too shy to tell me?",
  "What is the most vulnerable you have ever felt around me?",
  "Have you ever compared me to a past partner?",
  "What is something you want me to do to you that I have never done?",
  "What is the most jealous you have ever felt because of me?",
  "Have you ever thought about breaking up with me?",
  "What do you think about when you cannot sleep?",
  "What is something about your past that you think would change how I see you?",
  "What is the most attractive thing I do without realising it?",
  "Have you ever done something to make me jealous on purpose?",
  "What is the one thing you are most afraid to lose about our relationship?",
  "What is something you have always wanted to ask me but were afraid to?",
  "Have you ever lied about enjoying something we did together?",
  "What is a side of yourself you have never shown me?",
  "What do you think is our biggest weakness as a couple?",
  "Have you ever flirted with someone while we were together?",
  "What is something about me that you would change if you could?",
  "What is the most spontaneous thing you want us to do together?",
  "Have you ever been tempted to go through my phone?",
  "What is the most intimate non-physical moment we have shared?",
  "What is something you need more of from me emotionally?",
  "Have you ever had a dream about me that you were embarrassed to share?",
  "What is the one thing that makes you feel most connected to me?",
  "Have you ever doubted whether we were right for each other?",
  "What is something you do in private that you would be embarrassed for me to see?",
  "What is the most attractive quality your ex had that you wish I had?",
  "Have you ever lied about how many people you have been with?",
  "What is the wildest thought you have had about me?",
  "What is something I said that stayed with you longer than you expected?",
  "Have you ever been embarrassed by something I did in public?",
  "What is the most romantic thing you have ever done for anyone?",
  "Have you ever wanted to say something to me but stopped yourself?",
  "What is the one part of your body you are most self-conscious about?",
  "Have you ever pretended to be okay when you were not?",
  "What is something about our physical relationship you want to improve?",
  "What is the biggest risk you have ever taken for love?",
  "Have you ever sent a message meant for me to the wrong person?",
  "What is something you find attractive that you think I would judge you for?",
  "What is the most important lesson a past relationship taught you?",
  "Have you ever felt like I did not appreciate you enough?",
  "What is your love language and do you think I fulfil it?",
  "Have you ever regretted telling me something?",
  "What is something you wish I knew about you without having to say it?",
  "Have you ever been in love with more than one person at the same time?",
  "What is the most irrational thing jealousy has made you do?",
  "Have you ever kept something from me to protect my feelings?",
  "What is a dealbreaker you have that I might not know about?",
  "What is the most adventurous place you want to visit with me?",
  "Have you ever felt like you loved me more than I loved you?",
  "What is the most selfish thing you have ever done in a relationship?",
  "Have you ever gone through a phase where you were less attracted to me?",
  "What is something about our future together that excites you the most?",
  "Have you ever tested me to see how I would react?",
  "What is the one memory of us you never want to forget?",
  "Have you ever stayed in a moment with me wishing it would never end?",
  "What is something about how I love you that surprises you?",
  "Have you ever felt like you needed space from me but didn't say it?",
  "What is something you find physically attractive about me that is unconventional?",
  "Have you ever felt like you were not enough for me?",
  "What is the most honest thing you can say about how I make you feel?",
  "Have you ever wondered what our life would have been like if we never met?",
  "What is something you want us to experience together before the year ends?",
  "Have you ever caught yourself falling for me all over again unexpectedly?",
  "What is the most unattractive thing someone can do and have I ever done it?",
  "Have you ever wished I was more like someone else?",
  "What is the one thing you are most grateful for in our relationship?",
  "Have you ever felt like I was not listening to you properly?",
  "What is something you have sacrificed for this relationship?",
  "Have you ever regretted a decision we made together?",
  "What is something about intimacy that you have never told anyone?",
  "Have you ever felt more connected to me during a difficult time than a good one?",
  "What is the most honest thing you can say about your flaws as a partner?",
  "Have you ever blamed me for something that was not my fault?",
  "What is something you want to improve about yourself for the sake of our relationship?",
  "Have you ever felt like we were growing apart?",
  "What is a secret desire you have that you think I might not accept?",
  "Have you ever stayed quiet during an argument when you knew you were right?",
  "What is the most vulnerable question you could ask me right now?",
  "Have you ever cried because of something I said without me knowing?",
  "What is something you love about how we argue and make up?",
  "Have you ever felt pressure to be someone different around me?",
  "What is the most meaningful thing I have ever done for you?",
  "Have you ever wondered if I think about you as much as you think about me?",
  "What is one thing you want to change about how we communicate?",
  "Have you ever felt proud of me in a way you forgot to tell me?",
  "What is the one thing you are most afraid I will never understand about you?",
  "If you could relive one moment with me what would it be and why?",
];

export const COUPLES_DARES: string[] = [
  "Blindfold your partner and trace a word on their body with your finger. They must guess it.",
  "Give your partner a 60 second massage on a body part they choose.",
  "Whisper the most attractive thing about your partner slowly into their ear.",
  "Feed your partner something without using your hands.",
  "Kiss your partner somewhere other than their lips for 10 seconds.",
  "Let your partner draw something on your back and guess what it is.",
  "Describe what you want to do to your partner tonight in detail using only your eyes and gestures.",
  "Hold eye contact with your partner without speaking for 60 seconds.",
  "Let your partner do your hair however they want for the rest of the game.",
  "Whisper three things you love about your partner's body into their ear.",
  "Take a photo together in the most romantic pose you can think of.",
  "Give your partner a slow 30 second kiss wherever they choose.",
  "Let your partner blindfold you and surprise you with a gentle touch anywhere they choose.",
  "Tell your partner exactly what you were thinking the first time you found them attractive.",
  "Slow dance with your partner for one full minute with no music.",
  "Let your partner pick an outfit for you to wear for the rest of the game.",
  "Recreate your first kiss with your partner.",
  "Give your partner a 90 second foot or hand massage.",
  "Whisper the most detailed description of your favourite physical feature of theirs.",
  "Let your partner apply something to your lips and then kiss it off.",
  "Describe your partner's body using only food comparisons.",
  "Let your partner choose one place on your body to kiss for 15 seconds.",
  "Give your partner a back massage using only your forearms for 60 seconds.",
  "Write your partner's name somewhere on your body they will discover later.",
  "Do a dramatic reading of your most flirtatious text conversation with your partner.",
  "Let your partner direct you to kiss them exactly how and where they want for 30 seconds.",
  "Sit on your partner's lap for the next 3 turns.",
  "Let your partner smell your neck and describe what it makes them think of.",
  "Trace the outline of your partner's face with your fingertips with your eyes closed.",
  "Whisper something you have been wanting to do with your partner that you haven't done yet.",
  "Let your partner tie your hands together loosely for one full turn.",
  "Give your partner a 60 second scalp massage.",
  "Describe in detail what you would do if you had your partner completely alone tonight.",
  "Let your partner choose a song. You must slow dance and make real eye contact the entire time.",
  "Kiss your partner's hand slowly working up to their shoulder.",
  "Let your partner choose one item of your clothing to remove for the rest of the game.",
  "Describe your partner using only the senses — what they smell like, feel like, sound like.",
  "Sit back to back with your partner and take turns describing what you feel through the contact.",
  "Let your partner lead you around the room blindfolded using only touch.",
  "Whisper the most honest compliment you have never said out loud to your partner.",
  "Hold your partner's face in your hands and tell them one thing you see when you look at them.",
  "Let your partner choose where on your body they want you to apply something cold.",
  "Describe your ideal evening with your partner in as much sensory detail as possible.",
  "Let your partner whisper instructions to you for 30 seconds that you must follow exactly.",
  "Give your partner a kiss that lasts exactly as long as the group counts to 10.",
  "Let your partner choose your next dare from the dare pile sight unseen.",
  "Tell your partner the exact moment you knew you were falling for them.",
  "Let your partner remove one accessory from your body using only their mouth.",
  "Breathe on your partner's neck for 10 seconds without touching them.",
  "Let your partner choose one thing for you to say out loud that you have been holding back.",
  "Give your partner the most intense hug you can for 30 full seconds without letting go.",
  "Whisper a play by play of exactly what you want to happen between you two later tonight.",
  "Let your partner choose a body part. Massage it for 90 seconds.",
  "Press your forehead against your partner's and hold it there for 60 seconds in silence.",
  "Let your partner guide your hand to wherever they want it to rest for 30 seconds.",
  "Kiss your partner starting from their shoulder and work your way slowly to their jaw.",
  "Let your partner choose your sleeping position for tonight.",
  "Whisper the most vulnerable thing you feel when your partner looks at you.",
  "Give your partner a tour of what you love about their body using only words.",
  "Let your partner choose a playlist. You must respond to them physically however the music makes you feel.",
  "Look your partner in the eye and say the one thing you have been afraid to say.",
  "Let your partner run their fingers through your hair for 60 seconds while you sit still.",
  "Describe exactly how your partner makes you feel when they walk into a room.",
  "Let your partner choose where your next kiss lands.",
  "Take turns breathing in sync with each other for 90 seconds.",
  "Let your partner reposition you however they want for the next 2 turns.",
  "Whisper three things you want your partner to do to you.",
  "Give your partner a slow kiss on the back of their neck.",
  "Let your partner choose what you drink for the rest of the game.",
  "Describe the last time your partner made your heart race without trying.",
  "Let your partner hold your face and kiss you however they want for 20 seconds.",
  "Whisper your favourite thing about being physically close to your partner.",
  "Give your partner a 2 minute back scratch wherever they direct you.",
  "Let your partner take a candid photo of you to keep.",
  "Sit as close to your partner as physically possible for the next 5 turns.",
  "Let your partner choose one word. Use that word to describe them for the rest of the turn.",
  "Kiss your partner the way you wish you had kissed them the very first time.",
  "Let your partner hold your hand under the table for the next 3 turns.",
  "Describe your partner's touch using only weather metaphors.",
  "Let your partner whisper your biggest compliment back to you 3 times slowly.",
  "Give your partner a kiss that you have been saving for the right moment.",
  "Let your partner choose your seating position for the rest of the game.",
  "Trace the shape of your partner's lips with your fingertip very slowly.",
  "Let your partner choose one rule you must follow for the rest of the game.",
  "Tell your partner one physical thing they do that completely undoes you.",
  "Let your partner direct a 60 second kiss exactly how they want it.",
  "Whisper what you were thinking the last time you could not stop looking at your partner.",
  "Give your partner the most genuine smile you have and hold it for 30 seconds.",
  "Let your partner pick the side of the bed you sleep on tonight.",
  "Describe in detail what your favourite version of your partner looks like.",
  "Let your partner hold eye contact with you while you say three honest things about them.",
  "Kiss your partner slowly on their collarbone for 15 seconds.",
  "Let your partner reread the most romantic text you have ever sent them out loud.",
  "Whisper to your partner what you love most about being close to them.",
  "Give your partner a 60 second temple massage.",
  "Let your partner choose your next truth question instead of spinning.",
  "Tell your partner one thing you hope they never stop doing.",
  "Let your partner choose where you sit for the rest of the night.",
  "Give your partner the longest most genuine hug of the entire game right now.",
  "Final dare — both partners say one thing out loud they have never said to each other. No skipping.",
];
